### ISSUE TITLE
need initialization

### ISSUE THREAD

**Issue by zchrissirhcz** [vra/c-code#1]
The encryption algorithm illustrated in this sample code is simple, however, the executable may print out un-expected result, due to char array not initialized. Tested on Visual Studio Debug mode, input and output:

>123
>456烫烫烫烫烫烫烫烫烫烫烫烫烫烫烫烫烫烫烫烫烫烫烫烫烫烫烫烫烫烫烫烫烫烫烫烫烫烫烫烫烫烫烫烫烫烫烫烫烫烫烫烫烫烫烫烫?

To fix, we need add this line:

>memset(res, 0, sizeof(res));

**Comment by vra** [comment]
Okay I will fix it soon! Thanks!
